<a href="https://colab.research.google.com/github/jamaak/Predicting-Electric-Vehicle-Purchases/blob/rup/notebook/eda_rupa.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# EDA - PREDITCTION ELECTRIC VEHICLE :P

In [13]:
# Khusus Terminal
!git clone https://github.com/jamaak/Predicting-Electric-Vehicle-Purchases

Cloning into 'Predicting-Electric-Vehicle-Purchases'...
remote: Enumerating objects: 63, done.
remote: Counting objects: 100% (63/63), done.
remote: Compressing objects: 100% (42/42), done.
remote: Total 63 (delta 21), reused 48 (delta 11), pack-reused 0 (from 0)
Receiving objects: 100% (63/63), 13.76 MiB | 14.92 MiB/s, done.
Resolving deltas: 100% (21/21), done.

!pip install ydata_profiling -q

In [32]:
import os
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from ydata_profiling import ProfileReport
import subprocess

# print current path
print(subprocess.check_output(["pwd"]))

b'/content\n'

/tmp/ipykernel_1376/3474267034.py:6: DeprecationWarning:
    `import ydata_profiling` is deprecated and will not receive more updates.
    Please install fg-data-profiling via `pip install fg-data-profiling` and use `import data_profiling` instead.

  from ydata_profiling import ProfileReport

In [23]:
path = 'Predicting-Electric-Vehicle-Purchases/data/'

train_df = pd.read_csv(path+'train.csv')
test_df = pd.read_csv(path+'test.csv')

In [24]:
train_df.head()

,id,Age,Annual_Income_USD,Daily_Commute_km,Number_of_Cars_Owned,Charging_Stations_Near_Home,Charging_Stations_Near_Work,Environmental_Concern_Level,Gender,City_Type,Current_Car_Type,Home_Charging_Possible,Subsidy_Available,Range_Anxiety_Level,Will_Buy_EV
0,0,66,92887.0,23.4,2,3,7,1.0,Male,Suburban,Sedan,Yes,No,Low,No
1,1,38,30000.0,5.0,1,2,2,4.0,Male,Rural,SUV,Yes,No,Low,No
2,2,26,94389.0,36.8,1,8,15,5.0,Female,Urban,Sedan,No,Yes,Low,Yes
3,3,66,73580.0,23.7,2,6,9,3.0,Male,Suburban,Hatchback,Yes,No,Low,No
4,4,54,57898.0,50.8,1,2,3,3.0,Male,Suburban,Hatchback,Yes,No,Low,No

In [25]:
train_df.shape

(668665, 15)

In [35]:
profile = ProfileReport(
    train_df,
    title='Profiling Report',
    explorative=True,
)
profile.to_file('output_train.html')

# show in output
profile

Summarize dataset:   0%|          | 0/5 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]
  7%|▋         | 1/15 [00:00<00:09,  1.55it/s]
 27%|██▋       | 4/15 [00:01<00:03,  3.40it/s]
 40%|████      | 6/15 [00:01<00:01,  4.72it/s]
 47%|████▋     | 7/15 [00:02<00:02,  3.24it/s]
 53%|█████▎    | 8/15 [00:03<00:03,  1.98it/s]
 60%|██████    | 9/15 [00:04<00:04,  1.23it/s]
 67%|██████▋   | 10/15 [00:07<00:06,  1.22s/it]
 73%|███████▎  | 11/15 [00:09<00:06,  1.54s/it]
 80%|████████  | 12/15 [00:11<00:04,  1.60s/it]
 87%|████████▋ | 13/15 [00:13<00:03,  1.65s/it]
 93%|█████████▎| 14/15 [00:14<00:01,  1.53s/it]
100%|██████████| 15/15 [00:15<00:00,  1.02s/it]

Generate report structure:   0%|          | 0/1 [00:00<?, ?it/s]

Render HTML:   0%|          | 0/1 [00:00<?, ?it/s]

Export report to file:   0%|          | 0/1 [00:00<?, ?it/s]

In [36]:
profile

In [27]:
# simple stat like meann, median train_df dan test_df
test_df.describe()
train_df.describe()

,id,Age,Annual_Income_USD,Daily_Commute_km,Number_of_Cars_Owned,Charging_Stations_Near_Home,Charging_Stations_Near_Work,Environmental_Concern_Level
count,668665.00000,668665.000000,668665.000000,668665.000000,668665.000000,668665.000000,668665.000000,668665.000000
mean,334332.00000,47.039171,84769.266989,32.158298,1.712626,4.960408,7.176314,2.935477
std,193027.10321,12.875448,28648.029042,18.730474,0.729275,3.926843,5.186627,1.429119
min,0.00000,25.000000,30000.000000,5.000000,1.000000,0.000000,0.000000,1.000000
25%,167166.00000,36.000000,67376.000000,17.200000,1.000000,2.000000,3.000000,2.000000
50%,334332.00000,47.000000,84880.000000,33.600000,2.000000,4.000000,6.000000,3.000000
75%,501498.00000,58.000000,102753.000000,47.400000,2.000000,7.000000,10.000000,4.000000
max,668664.00000,69.000000,188549.000000,98.700000,4.000000,14.000000,19.000000,5.000000

In [28]:
# Check Target Value
# In this column, 1 = Bahwa customer akan membeli - 0 = Bahwa customer tidak akan membeli.

def check_target_value(column_name):
    """
    Calculates the count and percentage of each unique value in a specified column.

    Args:
        column_name (str): The name of the target column in the DataFrame.

    Returns:
        pd.DataFrame: A DataFrame with unique values, their counts, and percentages.
                      Returns None if the column does not exist.
    """
    if column_name not in df.columns:
        print(f"Error: Column '{column_name}' not found in the DataFrame.")
        return None

    counts = df[column_name].value_counts()
    percentages = (df[column_name].value_counts(normalize=True) * 100).round(2)

    result_df = pd.DataFrame({
        'Count': counts,
        'Percentage (%)': percentages
    })
    result_df.index.name = 'Unique Value'
    return result_df

##